---
- name: Git clone repository
  git:
    repo: https://github.com/janeczku/calibre-web.git
    dest: /var/www/calibre-{{ calibre_web.name }}
    version: '{{ calibre_version }}'
  ignore_errors: 'yes'

- name: Install requirements for root user
  command: python3 -m pip install --target vendor -r requirements.txt
  args:
    chdir: /var/www/calibre-{{ calibre_web.name }}

- name: Create systemctl service
  template:
    src: cps.service.j2
    dest: /etc/systemd/system/calibre-{{ calibre_web.name }}.service
    mode: 0644

- name: Create symlink to Sqlite database
  file:
    src: "{{ calibre_web.db_symlink_path }}"
    path: /var/www/calibre-{{ calibre_web.name }}/app.db
    state: link
  tags: calibre-db
  when: calibre_web.db_symlink_path is defined

- name: Copy Nginx conf
  template:
    src: nginx_conf.j2
    dest: /etc/nginx/sites-available/calibre-{{ calibre_web.name }}.conf
    mode: 0644
  notify: reload nginx

- name: symlink to site enabled
  file:
    src: /etc/nginx/sites-available/calibre-{{ calibre_web.name }}.conf
    path: /etc/nginx/sites-enabled/calibre-{{ calibre_web.name }}.conf
    state: link

- name: Enable {{ calibre_web.name }} service
  systemd:
    name: "calibre-{{ calibre_web.name }}.service"
    enabled: 'yes'
    state: restarted
    daemon_reload: 'yes'
  become: true
  notify: reload nginx
