---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - nginx
    - python3
    - python3-pip

- name: Install Calibre-Web
  include: install_calibre_web.yml

- name: Setup SSL for the domain
  include_role:
    name: haelle.certbot
  vars:
    certbot_install_method: snap
    certbot_create_if_missing: 'yes'
    certbot_create_method: standalone
    certbot_admin_email: "{{ calibre_web.certbot_email }}"
    certbot_certs:
      - domains:
        - "{{ calibre_web.fqdn }}"
